#!/bin/bash
#chkconfig: 2345 55 66
########################################
# this scripts is created by cj
#cj QQ:278028843
#site :
#time 20180401
############################################
. /etc/init.d/functions

if [ $# -ne 1 ];then
     usage: $0 {start|stop}
     exit 1
     fi

case "$1" in
start)
     /bin/bash /server/scripts/inotify_rsync.sh &
    echo $$ >/var/run/inotify.pid
    if [ `ps -ef|grep inotify|wc -l` -gt 2 ];then
       action "inotify server is started" /bin/true
    else
       action "inotify yserver is started" /bin/false
    fi
    ;;
stop)
    kill -9 `cat /var/run/inotify.pid` >/dev/null 2>&1
    pkill inotifywait
    sleep 2
    if [ `ps -ef|grep inotify|grep -v grep|wc -l` -eq 0 ];then
         action "inotify server is stopped" /bin/true
    else
         action "inotify server is stopped" /bin/false
    fi
   ;;
*)
    usage: $0 {start|stop}
   exit 1
esac
  
